// =============================================================
// STEAM CRON STUDIO — Docker Compose Generator
// =============================================================

import { TASKS_REGISTRY } from '../tasks-registry.js';

/**
 * Generate docker-compose.yml content
 * @param {Object} globalCfg
 * @param {Object} tasksCfg
 * @returns {string}
 */
export function generateDockerCompose(globalCfg, tasksCfg) {
  const enabledTasks   = TASKS_REGISTRY.filter(t => tasksCfg[t.id]?.enabled);
  const needsPlaywright = enabledTasks.some(t => t.outputFormat === 'image');
  const needsItad       = enabledTasks.some(t => t.requiresItad);

  const lines = [];

  lines.push(`# Docker Compose — Generated by Steam Cron Studio`);
  lines.push(`# https://github.com/abosalehg-ui/steam-cron-studio`);
  lines.push(``);
  lines.push(`version: "3.9"`);
  lines.push(``);
  lines.push(`services:`);
  lines.push(`  openclaw-steam:`);
  lines.push(`    image: openclaw/agent:latest`);
  lines.push(`    container_name: openclaw-steam`);
  lines.push(`    restart: unless-stopped`);

  if (needsPlaywright) {
    lines.push(`    shm_size: 2gb        # Required for Chromium/Playwright`);
  }

  lines.push(`    environment:`);
  lines.push(`      - STEAM_WEB_API_KEY=\${STEAM_WEB_API_KEY}`);
  lines.push(`      - OPENCLAW_TELEGRAM_BOT_TOKEN=\${OPENCLAW_TELEGRAM_BOT_TOKEN}`);
  if (needsItad) {
    lines.push(`      - ITAD_API_KEY=\${ITAD_API_KEY}`);
  }
  lines.push(`      - TZ=${globalCfg.timezone || 'Asia/Riyadh'}`);
  lines.push(`    volumes:`);
  lines.push(`      - ./cron_tasks.yaml:/app/cron_tasks.yaml:ro`);
  lines.push(`      - ./state:/app/state`);
  lines.push(`    logging:`);
  lines.push(`      driver: "json-file"`);
  lines.push(`      options:`);
  lines.push(`        max-size: "10m"`);
  lines.push(`        max-file: "3"`);
  lines.push(``);
  lines.push(`# .env file should contain:`);
  lines.push(`# STEAM_WEB_API_KEY=your_key_here`);
  lines.push(`# OPENCLAW_TELEGRAM_BOT_TOKEN=your_token_here`);
  if (needsItad) {
    lines.push(`# ITAD_API_KEY=your_key_here`);
  }
  lines.push(``);
  lines.push(`# Usage:`);
  lines.push(`# 1. Create .env file with the variables above`);
  lines.push(`# 2. Place cron_tasks.yaml next to this file`);
  lines.push(`# 3. mkdir state`);
  lines.push(`# 4. docker compose up -d`);

  return lines.join('\n') + '\n';
}
