// =============================================================
// STEAM CRON STUDIO — Systemd Generator
// Generates .service, .timer, and install.sh
// =============================================================

/**
 * Generate systemd service unit
 * @param {Object} globalCfg
 * @returns {string}
 */
export function generateService(globalCfg) {
  return `[Unit]
Description=OpenClaw Steam Monitoring Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=openclaw
WorkingDirectory=/opt/openclaw
ExecStart=/opt/openclaw/venv/bin/python -m openclaw run cron_tasks.yaml
Restart=on-failure
RestartSec=30s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=openclaw-steam

# Environment (add your keys here or use EnvironmentFile)
EnvironmentFile=/opt/openclaw/.env
Environment=TZ=${globalCfg.timezone || 'Asia/Riyadh'}

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Generate systemd timer unit
 * @returns {string}
 */
export function generateTimer() {
  return `[Unit]
Description=OpenClaw Steam — Scheduler Watchdog
After=network-online.target

[Timer]
# OpenClaw manages its own cron schedule internally.
# This timer acts as a watchdog to restart if agent crashes.
OnBootSec=60s
OnUnitActiveSec=5min

[Install]
WantedBy=timers.target
`;
}

/**
 * Generate install.sh bash script
 * @param {Object} globalCfg
 * @returns {string}
 */
export function generateInstallScript(globalCfg) {
  return `#!/usr/bin/env bash
# ============================================================
# OpenClaw Steam — Install Script
# Generated by Steam Cron Studio
# ============================================================
set -euo pipefail

SERVICE_USER="openclaw"
INSTALL_DIR="/opt/openclaw"
VENV_DIR="$INSTALL_DIR/venv"

echo "🎮 Installing OpenClaw Steam Monitoring Agent..."

# Create user (if not exists)
if ! id "$SERVICE_USER" &>/dev/null; then
  useradd --system --home-dir "$INSTALL_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
  echo "✅ Created user: $SERVICE_USER"
fi

# Create directories
mkdir -p "$INSTALL_DIR" "$INSTALL_DIR/state"
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Python venv + openclaw
if [ ! -d "$VENV_DIR" ]; then
  python3 -m venv "$VENV_DIR"
  "$VENV_DIR/bin/pip" install --upgrade pip
  "$VENV_DIR/bin/pip" install openclaw playwright
  "$VENV_DIR/bin/playwright" install chromium
  echo "✅ Python env created"
fi

# Copy config files
cp cron_tasks.yaml "$INSTALL_DIR/cron_tasks.yaml"
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/cron_tasks.yaml"

# .env file setup
if [ ! -f "$INSTALL_DIR/.env" ]; then
  cat > "$INSTALL_DIR/.env" << 'EOF'
STEAM_WEB_API_KEY=REPLACE_WITH_YOUR_KEY
OPENCLAW_TELEGRAM_BOT_TOKEN=REPLACE_WITH_YOUR_TOKEN
EOF
  chmod 600 "$INSTALL_DIR/.env"
  chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/.env"
  echo "⚠️  Created .env — please edit: $INSTALL_DIR/.env"
fi

# Install systemd units
cp openclaw-steam.service /etc/systemd/system/
cp openclaw-steam.timer   /etc/systemd/system/
systemctl daemon-reload

# Enable & start
systemctl enable --now openclaw-steam.service
systemctl enable --now openclaw-steam.timer

echo ""
echo "✅ OpenClaw installed successfully!"
echo ""
echo "📋 Next steps:"
echo "  1. Edit your API keys:  nano $INSTALL_DIR/.env"
echo "  2. Check status:        systemctl status openclaw-steam"
echo "  3. View logs:           journalctl -u openclaw-steam -f"
echo ""
echo "⚠️  Remember: NEVER commit your .env file to version control."
`;
}

/**
 * Generate all systemd files as an object
 * @param {Object} globalCfg
 * @returns {{ service: string, timer: string, install: string }}
 */
export function generateSystemd(globalCfg) {
  return {
    service: generateService(globalCfg),
    timer:   generateTimer(),
    install: generateInstallScript(globalCfg),
  };
}
