// =============================================================
// STEAM CRON STUDIO — YAML Generator
// Produces production-ready cron_tasks.yaml from builder config
// =============================================================

import { TASKS_REGISTRY } from '../tasks-registry.js';
import { cronToHuman }    from '../utils/cron-nl.js';

// ── Helpers ────────────────────────────────────────────────────
function yamlStr(value) {
  if (typeof value === 'string') {
    if (value.includes('\n') || value.includes('"') || value.includes("'") || value.includes(':') || value.includes('#')) {
      return `"${value.replace(/"/g, '\\"')}"`;
    }
    return value;
  }
  return String(value);
}

function indent(str, spaces = 2) {
  return str.split('\n').map(l => ' '.repeat(spaces) + l).join('\n');
}

function tagsToYaml(arr) {
  return '[' + arr.map(t => `"${t}"`).join(', ') + ']';
}

/**
 * Generate the full cron_tasks.yaml string
 * @param {Object} globalCfg   { steamId, chatId, region, currency, timezone }
 * @param {Object} tasksCfg    { [taskId]: { enabled, schedule, configs } }
 * @returns {string}
 */
export function generateYaml(globalCfg, tasksCfg) {
  const { steamId, chatId, region, currency, timezone } = globalCfg;
  const enabledTasks = TASKS_REGISTRY.filter(t => tasksCfg[t.id]?.enabled);

  const hasImageTask = enabledTasks.some(t => t.outputFormat === 'image');

  const lines = [];

  // ── Header ──
  lines.push(`# ============================================================`);
  lines.push(`# OpenClaw Cron Tasks — Steam Monitoring Suite v3.0`);
  lines.push(`# Generated by Steam Cron Studio`);
  lines.push(`# https://github.com/abosalehg-ui/steam-cron-studio`);
  lines.push(`# ============================================================`);
  lines.push(``);
  lines.push(`version: "3.0"`);
  lines.push(`agent: OpenClaw`);
  lines.push(``);

  // ── Globals ──
  lines.push(`globals:`);
  lines.push(`  timezone: ${timezone || 'Asia/Riyadh'}`);
  lines.push(`  locale: ar-SA`);
  lines.push(`  region_cc: ${region || 'sa'}`);
  lines.push(`  language: arabic`);
  lines.push(`  currency: ${currency || 'SAR'}`);
  lines.push(`  steam_api_key: "\${STEAM_WEB_API_KEY}"`);
  lines.push(`  steam_id: "${steamId || 'YOUR_STEAM_ID64'}"`);
  lines.push(`  itad_api_key: "\${ITAD_API_KEY}"`);
  lines.push(`  notification:`);
  lines.push(`    channel: telegram`);
  lines.push(`    chat_id: "${chatId || 'YOUR_CHAT_ID'}"`);
  lines.push(`    parse_mode: HTML`);
  lines.push(`    disable_web_page_preview: true`);
  lines.push(`  http:`);
  lines.push(`    timeout_seconds: 10`);
  lines.push(`    max_retries: 2`);
  lines.push(`    backoff: exponential`);
  lines.push(`  state_dir: "./state"`);
  lines.push(`  renders_dir: "./state/renders"`);
  lines.push(``);

  if (hasImageTask) {
    lines.push(`  rendering:`);
    lines.push(`    engine: playwright`);
    lines.push(`    browser: chromium`);
    lines.push(`    viewport:`);
    lines.push(`      width: 1080`);
    lines.push(`      height: 1920`);
    lines.push(`    device_scale_factor: 2`);
    lines.push(`    full_page: true`);
    lines.push(`    timeout_ms: 30000`);
    lines.push(`    wait_for: networkidle`);
    lines.push(``);
    lines.push(`  design_system:`);
    lines.push(`    theme: steam_dark`);
    lines.push(`    colors:`);
    lines.push(`      bg_gradient_start: "#1b2838"`);
    lines.push(`      bg_gradient_end:   "#2a475e"`);
    lines.push(`      card_bg:           "rgba(23, 44, 66, 0.85)"`);
    lines.push(`      card_border:       "rgba(102, 192, 244, 0.25)"`);
    lines.push(`      accent_gold:       "#c7a008"`);
    lines.push(`      accent_green:      "#5c7e10"`);
    lines.push(`      accent_red:        "#a94442"`);
    lines.push(`      accent_fire:       "#ff6b35"`);
    lines.push(`      text_primary:      "#c7d5e0"`);
    lines.push(`      text_secondary:    "#8f98a0"`);
    lines.push(`      text_white:        "#ffffff"`);
    lines.push(`    fonts:`);
    lines.push(`      arabic_primary:    "'Amiri', 'Scheherazade New', serif"`);
    lines.push(`      latin:             "'Inter', 'Segoe UI', sans-serif"`);
    lines.push(`      google_fonts_href: "https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Inter:wght@400;600;800&display=swap"`);
    lines.push(`    game_thumbnail_url: "https://cdn.cloudflare.steamstatic.com/steam/apps/{APPID}/header.jpg"`);
    lines.push(`    fallback_thumbnail: "https://cdn.cloudflare.steamstatic.com/steam/apps/{APPID}/capsule_616x353.jpg"`);
    lines.push(`    watermark: "Generated by OpenClaw · {date}"`);
    lines.push(``);
  }

  // ── Tasks ──
  lines.push(`# ============================================================`);
  lines.push(`# TASKS`);
  lines.push(`# ============================================================`);
  lines.push(`tasks:`);

  for (const task of enabledTasks) {
    const cfg      = tasksCfg[task.id]?.configs || {};
    const schedule = tasksCfg[task.id]?.schedule || task.schedule;
    const human    = cronToHuman(schedule);
    const humanStr = human.ar || human;

    lines.push(``);
    lines.push(`  # ${'─'.repeat(58)}`);
    lines.push(`  # ${task.name.ar} — ${task.name.en}`);
    lines.push(`  # Schedule: ${schedule} (${humanStr})`);
    lines.push(`  # Output: ${task.outputFormat.toUpperCase()}${task.privacyHigh ? ' | ⚠️ PRIVACY HIGH — never render as image' : ''}`);
    lines.push(`  # ${'─'.repeat(58)}`);
    lines.push(`  - id: ${task.id}`);
    lines.push(`    name: "${task.name.ar}"`);
    lines.push(`    schedule: "${schedule}"`);
    lines.push(`    enabled: true`);

    // Task-specific config overrides
    lines.push(`    config:`);
    for (const cfgDef of task.configs) {
      const val = cfg[cfgDef.key] ?? cfgDef.default;
      if (cfgDef.type === 'tags') {
        lines.push(`      ${cfgDef.key}: ${tagsToYaml(Array.isArray(val) ? val : cfgDef.default)}`);
      } else if (cfgDef.type === 'bool') {
        lines.push(`      ${cfgDef.key}: ${val ? 'true' : 'false'}`);
      } else {
        lines.push(`      ${cfgDef.key}: ${val}`);
      }
    }

    // Embed the full prompt (abbreviated — points to the task spec)
    lines.push(`    prompt: |`);
    lines.push(`      # Full prompt for ${task.id}`);
    lines.push(`      # Region: ${region || 'SA'} | Currency: ${currency || 'SAR'} | SteamID: ${steamId || 'YOUR_STEAM_ID64'}`);
    lines.push(`      # See full prompt spec: https://github.com/abosalehg-ui/steam-cron-studio/blob/main/examples/cron_tasks.example.yaml`);
    lines.push(`      You are OpenClaw, a Steam monitoring agent for region ${region?.toUpperCase() || 'SA'} (${currency || 'SAR'}).`);
    lines.push(`      Task: ${task.description.en}`);
    lines.push(`      SteamID64: ${steamId || 'YOUR_STEAM_ID64'}`);
    lines.push(`      Chat ID: ${chatId || 'YOUR_CHAT_ID'}`);
    lines.push(`      Refer to the full prompt spec in the examples/ directory.`);
    lines.push(`      output_format: ${task.outputFormat.toUpperCase()}`);
    if (task.privacyHigh) {
      lines.push(`      PRIVACY: HIGH — NEVER render as image. Send as text only.`);
    }
  }

  lines.push(``);

  // ── Shared State Files ──
  lines.push(`# ============================================================`);
  lines.push(`# SHARED STATE FILES`);
  lines.push(`# ============================================================`);
  lines.push(`state_files:`);
  lines.push(`  - path: ./state/owned_games.json`);
  lines.push(`  - path: ./state/wishlist.json`);
  lines.push(`  - path: ./state/picks_history.json`);
  lines.push(`  - path: ./state/achievement_suggestions_history.json`);
  lines.push(`  - path: ./state/fx_rates.json`);
  lines.push(`  - path: ./state/friends_wishlists.json`);
  lines.push(`  - path: ./state/itad_mappings.json`);
  lines.push(`  - path: ./state/archive/`);
  lines.push(``);

  // ── Required Env ──
  lines.push(`# ============================================================`);
  lines.push(`# ENVIRONMENT VARIABLES REQUIRED`);
  lines.push(`# ============================================================`);
  lines.push(`required_env:`);
  lines.push(`  - STEAM_WEB_API_KEY               # Steam Web API — all tasks`);
  lines.push(`  - OPENCLAW_TELEGRAM_BOT_TOKEN      # Telegram bot token`);
  if (enabledTasks.some(t => t.requiresItad)) {
    lines.push(`  - ITAD_API_KEY                     # IsThereAnyDeal — Task 7`);
  }
  lines.push(``);

  // ── Schedule Glance ──
  lines.push(`# ============================================================`);
  lines.push(`# SCHEDULE SUMMARY (${timezone || 'Asia/Riyadh'})`);
  lines.push(`# ============================================================`);
  for (const task of enabledTasks) {
    const schedule = tasksCfg[task.id]?.schedule || task.schedule;
    const human    = cronToHuman(schedule);
    const fmt      = task.outputFormat === 'image' ? '🖼️ IMAGE' : '📝 TEXT';
    lines.push(`# ${schedule.padEnd(16)} → ${task.name.ar.padEnd(28)} ${fmt}`);
  }

  return lines.join('\n') + '\n';
}
